### PR TITLE
diagramme_de_classe

### PR DESCRIPTION
**Pull request by HakiMohamed**

### CODE REVIEW

**Comment by HakiMohamed** [comment]
add dg_classe

**Review by HakiMohamed — COMMENTED** [review]
good

**Comment by HakiMohamed** [comment]
good

**Review by HakiMohamed — COMMENTED** [review]
good

**Comment by HakiMohamed** [comment]
good

**Comment by HakiMohamed** [comment]
c

**Review by HakiMohamed — COMMENTED** [review]
a

**Review by yassirrachad97 — COMMENTED** [review]
chi haja

**Comment by yassirrachad97** [comment]
fdsf

**Pull request merged**
